blank_issues_enabled: true
contact_links:
  - name: 💬 Join our Telegram Community
    url: https://t.me/baish_community
    about: Join our Telegram group for general questions and community discussions
  - name: 📧 Email Us
    url: mailto:contact@baish.com.ar
    about: Send us an email for direct communication
