name: Feature Request
description: Suggest a new feature or improvement for the BAISH website
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible.

  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when...

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - Low
        - Medium
        - High

  - type: dropdown
    id: category
    attributes:
      label: Category
      options:
        - UI/UX Improvement
        - New Content/Page
        - Performance
        - Accessibility
        - Multilingual Support
        - Event Management
        - Community Features
        - Other

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context, mockups, or screenshots about the feature request here.
